matrix:
  include:
  - language: python
    python: 3.5
    before_install: cd rekallpy
    install: pip3 install .
    script: python3 setup.py test
    deploy:
      skip_cleanup: true
      provider: pypi
      user: wcrichto
      password:
        secure: P9mXMalYDHHj+EXV35Fk0pNH4WpM17gKN9LOc/szhJhC2g5Q/Z9nfO/DJX43UhSnkELVtcGkEBFE7IOL0MoF0p3u0XR6vQEy8WPTmxjNyIDYZukgGumX/7S2faSR6rSU7ej1MIJYWq70j3KLilGZQtjFzhfHmpzZOCwo/CoMU8gs91oWCxVX5UjWy3RSxtpnpu46GwzxBGgOsJQcerlLGZM6k5IjgVdzeBBz7x18z4z4kp/x9+jNvV/wGLvHF4oWfMav8cbD8G3QXEj4c7TrBOVPfxGHfU9dVrAVwGu81509JCGNz2IpxbmLKCdJfmwnSuZ5C22bjvZWNPZKsywekT+jmwREG7JCcXn/sZw/RX/3rQM8jrpI565dxAFAVPkbtC1fwP/KrSH/Dvy/Pr4LCXHg8dPq9n4CANevNzOf8tYXPvJKIyjyPCn6rcIDw1rnsTqJWRIbdZenGTdI5Ovh8VIrGS6CL2Nb+aF56xHKbXflxZzX4uJ2OO7Uhe6NUbEchg1m6qZ/43lHrzJ2TppM8N32V/QuispP6FXLOzBHSK0ygKpqEqMpK7S2U0Ookr5rlOdZfxJw42oGVNuQIoyCG58IxpKED3TCVnHyJ+7n7ZSGwQtYIfYmjc1BPaTcmkWWa9iuX7kbASMesRhKMpws+bOL9mIWcruVHNpX9Q5gus4=
      on:
        tags: true
        distributions: sdist bdist_wheel
  - language: node_js
    node_js: 10
    before_install: cd rekalljs
    install: npm install && npm run prepublishOnly
    script: npm run test
    deploy:
      provider: npm
      email: wcrichto@cs.stanford.edu
      api_key:
        secure: PeTs61hQndrn33zeJceUhJ2T+1jHNgdpRKA1VwoGTBTwyWoTfbmYhI7sDPAwATDDU29kvHI8lKAFXny6wgieWATFxzwAJnCS4KXDkoj+OwFDkacK7vj4aVDjeX/1Bz4peM68ruLgunTSClUsKSUFEafx06A0NX3zeT+eA0LczWp7k2EysnilbxNXhuFMHA1jP0AChkwuNJdRcMjSMSltTOSsmrqhiPfLsTNuzleu8xFJvmWT0wWb8FXoMQCFAoD/ZaaYmrPfOJagfOym/wPmteAeaEBQEEKVLgkkwstwd8Pt0sdb/Ysh/mIICp7wr4eLnkACbx+ANvjYKQlcjVZpcDi/OMcwLmZB+gebPsrbVxouCvqvinEwDMQIdSOPgU3C6wTa8neOkY0Dx6mVZspjO6z23dI6EWF9kuukjbJle8tESxpI62kXNjZKMHN04VfhaN6v/Rn+qTdn1HkGcc5lA0UfLhK+f4Nh1N0ChMenmvrweIQMImeUF1NJQTxsi9y+QHcLDtn84X480PDkilmsTEYk+GgVakyJ9TqZsXz2ZrFnyUbZOF5ACMhHAQzpzUynOK+aHK55B/6z1xRDHiHDb976Er8nnx4yyurEda45WwBZUKyXg0zLArAOsTvVKm2FzG3JCD2zDN0279VogC29lLghn5pB+7tIT0DIfuAvJtI=
      skip_cleanup: true
      on:
        tags: true
